import React from "react";
import { Link, useParams } from "react-router-dom";
import { Download, ChevronLeft, Building2, MessageSquareWarning } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getProperty } from "@/data/properties";
import { useStatuses } from "@/hooks/useData";
import PropertyNotFound from "@/components/common/PropertyNotFound";
import Panel from "@/components/common/Panel";
import InfoGrid from "@/components/common/InfoGrid";
import DemoTag from "@/components/common/DemoTag";
import PropertyPhoto from "@/components/common/PropertyPhoto";
import Twin3DPreview from "@/components/property/Twin3DPreview";
import HistoryCard from "@/components/property/HistoryCard";
import DocumentsCard from "@/components/property/DocumentsCard";
import ComplaintHistoryCard from "@/components/property/ComplaintHistoryCard";
import VerificationCard from "@/components/property/VerificationCard";
import { propertyFields } from "@/components/property/propertyFields";

export default function PropertyRecord() {
  const { id } = useParams();
  const p = getProperty(id);
  const statuses = useStatuses();
  if (!p) return <PropertyNotFound />;
  const s = statuses.get(id);
  const fields = [
    { label: "Property Name", value: p.name },
    { label: "ULPIN", value: s.ulpin ? `${s.ulpin} (Demo ULPIN)` : "Not Assigned", mono: !!s.ulpin },
    ...propertyFields(p, s),
  ];

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <Link to={`/property/${id}`} className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-ink"><ChevronLeft className="w-4 h-4" />Property Details</Link>
        <div className="flex gap-2">
          <Button asChild variant="outline"><Link to={`/complaints/new?property=${id}`}><MessageSquareWarning className="w-4 h-4 mr-2" />Raise Complaint</Link></Button>
          <Button onClick={() => window.print()}><Download className="w-4 h-4 mr-2" />Download Property Record</Button>
        </div>
      </div>

      <header className="bg-card border border-line rounded-2xl p-6 lg:p-8 print-card">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-5">
          <div>
            <p className="text-[11px] font-bold tracking-[0.2em] text-primary">DIGITAL PROPERTY RECORD</p>
            <h1 className="mt-2 text-2xl lg:text-3xl font-bold text-ink">{p.name}</h1>
            <p className="text-sm text-muted-foreground mt-1">{p.location}</p>
          </div>
          <div className="text-right">
            <DemoTag>Prototype record · Demo Data</DemoTag>
            <p className="text-xs text-muted-foreground mt-2">Generated {new Date().toLocaleDateString("en-IN")}</p>
          </div>
        </div>
        <div className="mt-6 grid md:grid-cols-[1fr_260px] gap-6">
          <InfoGrid items={fields} cols="sm:grid-cols-2 lg:grid-cols-3" />
          <PropertyPhoto property={p} className="aspect-[4/3] rounded-lg" />
        </div>
      </header>

      <div className="grid lg:grid-cols-2 gap-6">
        <Panel title="3D Digital Twin Preview" bodyClass="p-3"><Twin3DPreview property={p} className="h-72" /></Panel>
        <Panel title="Floor Structure" icon={Building2}>
          <table className="w-full text-sm">
            <thead className="text-left text-xs text-muted-foreground"><tr><th className="pb-2">Level</th><th className="pb-2">Use</th><th className="pb-2 text-right">Rooms</th></tr></thead>
            <tbody>
              {[...p.floors].reverse().map((f) => (
                <tr key={f.key} className="border-t border-line"><td className="py-2 font-medium">{f.name}</td><td className="py-2 text-muted-foreground">{f.summary}</td><td className="py-2 text-right font-mono">{f.rooms.filter((r) => !r.core).length}</td></tr>
              ))}
            </tbody>
          </table>
        </Panel>
      </div>
      <div className="grid lg:grid-cols-2 gap-6">
        <VerificationCard property={p} />
        <HistoryCard property={p} />
      </div>
      <DocumentsCard property={p} />
      <ComplaintHistoryCard property={p} />
      <p className="text-xs text-muted-foreground text-center">This record is generated by a prototype for demonstration. It is not an official government-issued property record.</p>
    </div>
  );
}